site_name: aws-iot-core-create-many-things-boto3
site_url: https://github.com/yilmaznaslan/aws-iot-core-create-many-things-boto3
site_description: Project documentation with Markdown.
site_author: MkDocs Team

repo_url: https://github.com/mkdocs/mkdocs/
edit_uri: ""
site_dir : 'docs'
docs_dir : 'markdown'
theme:
    name: readthedocs
    locale: en
    analytics: {gtag: 'G-274394082'}
    highlightjs: true


nav:
    - Home: index.md
    - User Guide: user_guide.md
    - Developer Guide:  devops_guide.md
    - Developer Guide(add):  dev_guide.md
    - Resources:
        - ssl_guide.md
    