site_name: MkDocs
site_url: https://www.mkdocs.org/
site_description: Project documentation with Markdown.
site_author: MkDocs Team

repo_url: https://github.com/mkdocs/mkdocs/
edit_uri: ""

theme:
    name: readthedocs
    locale: en
    analytics: {gtag: 'G-274394082'}
    highlightjs: true


nav:
    - Home: index.md
    - Introduction: introduction.md
    - Developer Guide:
        - dev_guide.md
    - Resources:
        - ssl_guide.md
    